import Header from "@/components/HeaderComponents/header/Header";
import Sidebar from "@/components/SideBarComponents/sidebar/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "@/context/ThemeContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calendar App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="anonymous"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
            rel="stylesheet"
          />
        </Head>
        <body className={inter.className}>
          <Header />
          <main>
            <Sidebar />
            <div className="main-content">
              <Toaster position="bottom-left" />
              {children}
            </div>
          </main>
        </body>
      </html>
    </ThemeProvider>
  );
}
